version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns: ["*"]

  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    groups:
      frontend-production:
        dependency-type: production
        patterns: ["*"]
      frontend-development:
        dependency-type: development
        patterns: ["*"]

  - package-ecosystem: pip
    directory: /backend
    schedule:
      interval: weekly
    groups:
      backend-python:
        patterns: ["*"]

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /backend
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /nginx
    schedule:
      interval: weekly
