import type { TranslationKey } from "../../i18n";

/** 将章节 ID 映射到其关联的 i18n 键列表，用于全文搜索 */
export const SECTION_CONTENT_KEYS: Record<string, TranslationKey[]> = {
  introduction: [
    "docsPage.intro.title", "docsPage.intro.p1",
    "docsPage.intro.f1.title", "docsPage.intro.f1.body",
    "docsPage.intro.f2.title", "docsPage.intro.f2.body",
    "docsPage.intro.f3.title", "docsPage.intro.f3.body",
    "docsPage.intro.f4.title", "docsPage.intro.f4.body",
    "docsPage.intro.f5.title", "docsPage.intro.f5.body",
    "docsPage.intro.f6.title", "docsPage.intro.f6.body",
    "docsPage.intro.newHere.title", "docsPage.intro.newHere.body",
  ],
  quickstart: [
    "docsPage.qs.title", "docsPage.qs.p1",
    "docsPage.qs.s1.title", "docsPage.qs.s1.body",
    "docsPage.qs.s2.title", "docsPage.qs.s2.body",
    "docsPage.qs.s3.title", "docsPage.qs.s3.body",
  ],
  authentication: [
    "docsPage.auth.title", "docsPage.auth.desc",
    "docsPage.auth.headersTitle", "docsPage.auth.row1", "docsPage.auth.row2", "docsPage.auth.row3",
    "docsPage.auth.tip.title", "docsPage.auth.tip.body",
    "docsPage.auth.responseHeaders.title",
    "docsPage.auth.responseHeaders.requestId", "docsPage.auth.responseHeaders.resolvedModel",
    "docsPage.auth.responseHeaders.fallbackFrom",
  ],
  "base-urls": [
    "docsPage.baseUrl.title", "docsPage.baseUrl.desc", "docsPage.baseUrl.note",
  ],
  models: [
    "docsPage.models.title", "docsPage.models.desc",
    "docsPage.models.list.title", "docsPage.models.list.body",
    "docsPage.models.alias.title", "docsPage.models.alias.body",
    "docsPage.models.linkBody",
  ],
  errors: [
    "docsPage.errors.title", "docsPage.errors.desc",
    "docsPage.errors.when",
    "docsPage.errors.e200", "docsPage.errors.e400", "docsPage.errors.e401",
    "docsPage.errors.e403", "docsPage.errors.e404", "docsPage.errors.e422",
    "docsPage.errors.e429", "docsPage.errors.e500", "docsPage.errors.e503",
  ],
  "rate-limits": [
    "docsPage.rate.title", "docsPage.rate.desc", "docsPage.rate.night",
    "docsPage.rate.tiers.title", "docsPage.rate.tiers.desc",
    "docsPage.rate.tiers.colLevel", "docsPage.rate.tiers.colRpm",
    "docsPage.rate.tiers.colTpm", "docsPage.rate.tiers.colApply",
    "docsPage.rate.tiers.default", "docsPage.rate.tiers.defaultApply",
    "docsPage.rate.tiers.high", "docsPage.rate.tiers.highApply",
    "docsPage.rate.tiers.unlimited", "docsPage.rate.tiers.unlimitedApply",
    "docsPage.rate.tiers.unlimitedValue",
    "docsPage.rate.headers.title",
    "docsPage.rate.h1", "docsPage.rate.h2", "docsPage.rate.h3", "docsPage.rate.h4",
  ],
  pagination: [
    "docsPage.pagination.title", "docsPage.pagination.desc", "docsPage.pagination.intro",
  ],
  versioning: [
    "docsPage.versioning.title", "docsPage.versioning.desc", "docsPage.versioning.intro",
    "docsPage.versioning.header.title", "docsPage.versioning.header.body",
    "docsPage.versioning.stability.title", "docsPage.versioning.stability.body",
    "docsPage.versioning.deprecation.title", "docsPage.versioning.deprecation.body",
  ],
  "chat-api": [
    "docsPage.chatApi.title", "docsPage.chatApi.desc",
    "docsPage.chatApi.streaming.title", "docsPage.chatApi.streaming.body",
    "docsPage.chatApi.json.title", "docsPage.chatApi.json.body",
    "docsPage.chatRequest.title",
    "docsPage.chatRequest.model", "docsPage.chatRequest.messages",
    "docsPage.chatRequest.stream", "docsPage.chatRequest.temperature",
    "docsPage.chatRequest.maxTokens", "docsPage.chatRequest.tools",
    "docsPage.chatRequest.responseFormat",
  ],
  "thinking-mode": [
    "docsPage.thinkingMode.title", "docsPage.thinkingMode.desc",
    "docsPage.thinkingMode.intro",
    "docsPage.thinkingMode.param.title", "docsPage.thinkingMode.param.body",
  ],
  vision: [
    "docsPage.vision.title", "docsPage.vision.desc",
    "docsPage.vision.image.title", "docsPage.vision.image.body",
    "docsPage.vision.image.param.model", "docsPage.vision.image.param.messages",
    "docsPage.vision.image.param.maxTokens",
    "docsPage.vision.ocr.title", "docsPage.vision.ocr.body",
    "docsPage.vision.ocr.param.model", "docsPage.vision.ocr.param.image",
  ],
  "tool-use": [
    "docsPage.toolUse.title", "docsPage.toolUse.desc", "docsPage.toolUse.flow.body",
    "docsPage.toolUse.param.model", "docsPage.toolUse.param.messages",
    "docsPage.toolUse.param.tools", "docsPage.toolUse.param.toolChoice",
  ],
  "embeddings-rerank": [
    "docsPage.embeddingsRerank.title", "docsPage.embeddingsRerank.desc",
    "docsPage.embeddingsRerank.embedding.title", "docsPage.embeddingsRerank.embedding.body",
    "docsPage.embeddingsRerank.embedding.param.model", "docsPage.embeddingsRerank.embedding.param.input",
    "docsPage.embeddingsRerank.rerank.title", "docsPage.embeddingsRerank.rerank.body",
    "docsPage.embeddingsRerank.rerank.param.model", "docsPage.embeddingsRerank.rerank.param.query",
    "docsPage.embeddingsRerank.rerank.param.documents", "docsPage.embeddingsRerank.rerank.param.topN",
  ],
  completions: [
    "docsPage.completions.title", "docsPage.completions.body",
    "docsPage.completions.param.model", "docsPage.completions.param.prompt",
    "docsPage.completions.param.maxTokens", "docsPage.completions.param.temperature",
    "docsPage.completions.param.stop", "docsPage.completions.param.stream",
  ],
  responses: [
    "docsPage.responses.title", "docsPage.responses.body",
    "docsPage.responses.metering.body",
    "docsPage.responses.param.model", "docsPage.responses.param.input",
    "docsPage.responses.param.instructions", "docsPage.responses.param.tools",
    "docsPage.responses.param.temperature", "docsPage.responses.param.stream",
  ],
  messages: [
    "docsPage.messages.title", "docsPage.messages.body",
    "docsPage.messages.param.model", "docsPage.messages.param.maxTokens",
    "docsPage.messages.param.messages", "docsPage.messages.param.system",
    "docsPage.messages.param.temperature", "docsPage.messages.param.stream",
  ],
  "count-tokens": [
    "docsPage.countTokens.title", "docsPage.countTokens.body",
    "docsPage.countTokens.param.model", "docsPage.countTokens.param.messages",
  ],
  changelog: [
    "docsPage.changelog.title", "docsPage.changelog.desc", "docsPage.changelog.note",
    "docsPage.changelog.v1.date", "docsPage.changelog.v1.tag", "docsPage.changelog.v1.body",
    "docsPage.changelog.v2.date", "docsPage.changelog.v2.tag", "docsPage.changelog.v2.body",
    "docsPage.changelog.v3.date", "docsPage.changelog.v3.tag", "docsPage.changelog.v3.body",
  ],
  "multi-turn": [
    "docsPage.multiTurn.title", "docsPage.multiTurn.desc", "docsPage.multiTurn.intro",
  ],
  "json-mode": [
    "docsPage.jsonMode.title", "docsPage.jsonMode.desc", "docsPage.jsonMode.intro",
    "docsPage.jsonMode.strict.title", "docsPage.jsonMode.strict.body",
  ],
  "token-usage": [
    "docsPage.tokenUsage.title", "docsPage.tokenUsage.desc",
    "docsPage.tokenUsage.intro", "docsPage.tokenUsage.where", "docsPage.tokenUsage.streaming",
  ],
  "context-caching": [
    "docsPage.contextCaching.title", "docsPage.contextCaching.desc",
    "docsPage.contextCaching.intro", "docsPage.contextCaching.how",
  ],
  infrastructure: [
    "docsPage.infrastructure.title", "docsPage.infrastructure.desc",
    "docsPage.infrastructure.items.rateLimit.title", "docsPage.infrastructure.items.rateLimit.desc",
    "docsPage.infrastructure.items.roundRobin.title", "docsPage.infrastructure.items.roundRobin.desc",
    "docsPage.infrastructure.items.forward.title", "docsPage.infrastructure.items.forward.desc",
    "docsPage.infrastructure.items.metering.title", "docsPage.infrastructure.items.metering.desc",
    "docsPage.infrastructure.items.redisSentinel.title", "docsPage.infrastructure.items.redisSentinel.desc",
    "docsPage.infrastructure.items.hotCache.title", "docsPage.infrastructure.items.hotCache.desc",
    "docsPage.infrastructure.items.disconnectGuard.title", "docsPage.infrastructure.items.disconnectGuard.desc",
    "docsPage.infrastructure.items.fallback.title", "docsPage.infrastructure.items.fallback.desc",
    "docsPage.flow.nodes.fallback.title", "docsPage.flow.nodes.fallback.desc",
  ],
  "agent-tools": [
    "docsPage.agentTools.title", "docsPage.agentTools.desc",
    "docsPage.scenarios.codex.title", "docsPage.scenarios.codex.desc",
    "docsPage.scenarios.ccTool.title", "docsPage.scenarios.ccTool.desc",
    "docsPage.scenarios.kilo.title", "docsPage.scenarios.kilo.desc",
  ],
  faq: [
    "docsPage.faq.title", "docsPage.faq.desc",
    "docsPage.faq.q1.title", "docsPage.faq.q1.body",
    "docsPage.faq.q2.title", "docsPage.faq.q2.body",
    "docsPage.faq.q3.title", "docsPage.faq.q3.body",
    "docsPage.faq.q4.title", "docsPage.faq.q4.body",
    "docsPage.faq.q5.title", "docsPage.faq.q5.body",
  ],
  "usage-logs": [
    "docsPage.usageLogs.title", "docsPage.usageLogs.desc",
    "docsPage.usageLogs.recording.title", "docsPage.usageLogs.recording.body",
    "docsPage.usageLogs.troubleshoot.title", "docsPage.usageLogs.troubleshoot.body",
    "docsPage.usageLogs.retention.title", "docsPage.usageLogs.retention.body",
    "docsPage.usageLogs.cost.title", "docsPage.usageLogs.cost.body",
    "docsPage.usageLogs.streaming.title", "docsPage.usageLogs.streaming.body",
    "docsPage.usageLogs.analytics.title", "docsPage.usageLogs.analytics.body",
    "docsPage.usageLogs.fallback.title", "docsPage.usageLogs.fallback.body",
    "docsPage.usageLogs.usage.title", "docsPage.usageLogs.usage.body",
    "docsPage.usageLogs.logs.title", "docsPage.usageLogs.logs.body",
  ],
  "night-batch": [
    "docsPage.nightBatch.title", "docsPage.nightBatch.desc",
    "docsPage.nightBatch.window.title", "docsPage.nightBatch.window.body",
    "docsPage.nightBatch.endpoints.title",
    "docsPage.nightBatch.notice.title", "docsPage.nightBatch.notice.body",
    "docsPage.nightBatch.row1", "docsPage.nightBatch.row2",
  ],
  "best-practices": [
    "docsPage.bestPractices.title", "docsPage.bestPractices.desc",
    "docsPage.bestPractices.streaming.title", "docsPage.bestPractices.streaming.body",
    "docsPage.bestPractices.retry.title", "docsPage.bestPractices.retry.body",
    "docsPage.bestPractices.context.title", "docsPage.bestPractices.context.body",
    "docsPage.bestPractices.security.title", "docsPage.bestPractices.security.body",
    "docsPage.bestPractices.alias.title", "docsPage.bestPractices.alias.body",
    "docsPage.bestPractices.monitor.title", "docsPage.bestPractices.monitor.body",
  ],
  "api-reference/endpoints": [
    "docsPage.reference.endpoints.title", "docsPage.reference.endpoints.desc",
    "docsPage.reference.endpoints.sectionInference",
    "docsPage.reference.endpoints.sectionPublic",
    "docsPage.reference.endpoints.sectionUser",
    "docsPage.reference.endpoints.sectionForum",
    "docsPage.reference.endpoints.sectionAdmin",
    "docsPage.reference.endpoints.sectionNightBatch",
    "docsPage.reference.endpoints.chatCompletions",
    "docsPage.reference.endpoints.betaChatCompletions",
    "docsPage.reference.endpoints.completions",
    "docsPage.reference.endpoints.embeddings",
    "docsPage.reference.endpoints.responses",
    "docsPage.reference.endpoints.rerank",
    "docsPage.reference.endpoints.imageGenerations",
    "docsPage.reference.endpoints.ocr",
    "docsPage.reference.endpoints.messages",
    "docsPage.reference.endpoints.countTokens",
    "docsPage.reference.endpoints.models",
    "docsPage.reference.endpoints.modelDetail",
    "docsPage.reference.endpoints.publicConfig",
    "docsPage.reference.endpoints.publicStatus",
    "docsPage.reference.endpoints.publicStatusBreakdown",
    "docsPage.reference.endpoints.publicStatusToolCalls",
    "docsPage.reference.endpoints.publicStatusContextLength",
    "docsPage.reference.endpoints.publicStatusHeatmap",
    "docsPage.reference.endpoints.publicSceneTypes",
    "docsPage.reference.endpoints.publicModels",
    "docsPage.reference.endpoints.publicModelDetail",
    "docsPage.reference.endpoints.notifications",
    "docsPage.reference.endpoints.docFeedback",
    "docsPage.reference.endpoints.apply",
    "docsPage.reference.endpoints.applyRate",
    "docsPage.reference.endpoints.upgradeApply",
    "docsPage.reference.endpoints.userEarlyAccess",
    "docsPage.reference.endpoints.userStats",
    "docsPage.reference.endpoints.userStatsScenes",
    "docsPage.reference.endpoints.userStatsBreakdown",
    "docsPage.reference.endpoints.userStatsToolCalls",
    "docsPage.reference.endpoints.userStatsHeatmapWeek",
    "docsPage.reference.endpoints.userLogs",
    "docsPage.reference.endpoints.userRateLimits",
    "docsPage.reference.endpoints.userKeys",
    "docsPage.reference.endpoints.userKeyRegenerate",
    "docsPage.reference.endpoints.userKeyTier",
    "docsPage.reference.endpoints.userKeyUsage",
    "docsPage.reference.endpoints.askDocs",
    "docsPage.reference.endpoints.userForumOverview",
    "docsPage.reference.endpoints.userForumPosts",
    "docsPage.reference.endpoints.userForumCreatePost",
    "docsPage.reference.endpoints.userForumPostDetail",
    "docsPage.reference.endpoints.userForumReply",
    "docsPage.reference.endpoints.userForumLike",
    "docsPage.reference.endpoints.userForumFollow",
    "docsPage.reference.endpoints.userForumResolve",
    "docsPage.reference.endpoints.userForumPin",
    "docsPage.reference.endpoints.adminLogin",
    "docsPage.reference.endpoints.adminModels",
    "docsPage.reference.endpoints.adminFallback",
    "docsPage.reference.endpoints.adminConnectivityTest",
    "docsPage.reference.endpoints.adminSceneTypes",
    "docsPage.reference.endpoints.adminKeys",
    "docsPage.reference.endpoints.adminApplications",
    "docsPage.reference.endpoints.adminUpgradeApps",
    "docsPage.reference.endpoints.adminEarlyAccess",
    "docsPage.reference.endpoints.adminUsers",
    "docsPage.reference.endpoints.adminStatsDaily",
    "docsPage.reference.endpoints.adminStatsMonthly",
    "docsPage.reference.endpoints.adminStatsByModel",
    "docsPage.reference.endpoints.adminStatsByProject",
    "docsPage.reference.endpoints.adminStatsByUser",
    "docsPage.reference.endpoints.adminStatsOverview",
    "docsPage.reference.endpoints.adminStatsExtended",
    "docsPage.reference.endpoints.adminUsage",
    "docsPage.reference.endpoints.adminUsageStats",
    "docsPage.reference.endpoints.adminUsageStream",
    "docsPage.reference.endpoints.adminInfra",
    "docsPage.reference.endpoints.adminAskDocs",
    "docsPage.reference.endpoints.adminDocFeedback",
    "docsPage.reference.endpoints.adminReports",
    "docsPage.reference.endpoints.adminReportDetail",
    "docsPage.reference.endpoints.adminAudit",
    "docsPage.reference.endpoints.adminMigration",
    "docsPage.reference.endpoints.adminMigrationBaseline",
    "docsPage.reference.endpoints.adminContent",
    "docsPage.reference.endpoints.nightBatch",
    "docsPage.reference.endpoints.nightBatchPatch",
    "docsPage.reference.endpoints.nightBatchSeries",
  ],
};
