#!/usr/bin/env bash
# Fail fast when a source snapshot contains private keys, database exports,
# local environment files, or generated bytecode. Run from CI and before release.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${ROOT}"

failed=0

echo "▶ 检查开源许可证"
if [[ ! -f LICENSE && ! -f LICENSE.md ]]; then
  echo "✗ 缺少 LICENSE；版权方选择并批准许可证前不得公开发布" >&2
  failed=1
fi

echo "▶ 检查私钥标记"
if rg -n --with-filename --hidden -S \
  -e '-----BEGIN [A-Z ]*PRIVATE KEY-----' \
  --glob '!.git/**' \
  --glob '!**/node_modules/**' \
  --glob '!**/.venv/**' \
  --glob '!frontend/dist/**' \
  --glob '!offline-images/**' \
  --glob '!scripts/check-public-release.sh' \
  .; then
  echo "✗ 发现私钥标记；上述文件不得进入公开发行包" >&2
  failed=1
fi

echo "▶ 检查常见明文令牌与原组织标识"
if rg -n --with-filename --hidden -S \
  -e 'AKIA[0-9A-Z]{16}' \
  -e 'gh[pousr]_[A-Za-z0-9]{30,}' \
  -e 'sk-[A-Za-z0-9_-]{24,}' \
  -e 'BRDC\.ai|大数据应用部|\bdpmp\b' \
  --glob '!.git/**' \
  --glob '!**/node_modules/**' \
  --glob '!**/.venv/**' \
  --glob '!frontend/dist/**' \
  --glob '!scripts/check-public-release.sh' \
  .; then
  echo "✗ 发现疑似令牌或原组织标识；请逐项确认并清理" >&2
  failed=1
fi

echo "▶ 检查数据库导出与本地密钥文件"
while IFS= read -r path; do
  echo "✗ 不得发布：${path}" >&2
  failed=1
done < <(
  find . -type f \
    \( -iname '*.dump' -o -iname '*.backup' -o -iname '*.sql' -o -name '.env' \
       -o -iname '*.pem' -o -iname '*.key' -o -iname '*.p12' -o -iname '*.pfx' \) \
    -not -path './.git/*' \
    -not -path '*/node_modules/*' \
    -not -path '*/.venv/*' \
    -not -path './offline-images/*' \
    -print
)

echo "▶ 检查本地构建缓存"
while IFS= read -r path; do
  echo "✗ 发布前应移除本地缓存：${path}" >&2
  failed=1
done < <(
  find . \
    \( -path './.git' -o -path '*/node_modules' -o -path '*/.venv' \) -prune -o \
    -type f \( -name '*.pyc' -o -name '*.pyo' -o -name '.DS_Store' \) -print
)

if git ls-files '*.dump' '*.backup' '*.sql' | grep -q .; then
  echo "✗ Git 索引中存在数据库导出文件" >&2
  git ls-files '*.dump' '*.backup' '*.sql' >&2
  failed=1
fi

echo "▶ 检查 Git 历史对象路径"
history_paths="$({ git rev-list --objects --all || true; } | awk '{$1=""; sub(/^ /, ""); print}')"
if printf '%s\n' "${history_paths}" | rg -n -i \
  '(^|/)(\.env|bak)(/|$)|\.(dump|backup|sql|pem|p12|pfx)$|brdc|dpmp'; then
  echo "✗ Git 历史仍包含敏感/内部资产路径；请从干净仓库发布或验证历史重写" >&2
  failed=1
fi

git diff --check

if (( failed )); then
  exit 1
fi
echo "✔ 当前源码快照通过开源发布检查"
