#!/usr/bin/env bash
# Fail fast when a source snapshot contains private keys, database exports,
# local environment files, or generated bytecode. Run from CI and before release.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${ROOT}"

if ! command -v rg >/dev/null 2>&1; then
  echo "✗ 发布卫生检查需要 ripgrep (rg)，当前环境未安装" >&2
  exit 2
fi

failed=0

echo "▶ 检查开源许可证"
if [[ ! -f LICENSE && ! -f LICENSE.md ]]; then
  echo "✗ 缺少 LICENSE；版权方选择并批准许可证前不得公开发布" >&2
  failed=1
fi

echo "▶ 检查安全基线与工作流"
for required in \
  SECURITY.md \
  docs/SECURITY_BASELINE.md \
  docs/THREAT_MODEL.md \
  docs/ASVS-5.0-L2.md \
  docs/RUNTIME_SECURITY.md \
  docs/SECURITY_EXCEPTION_TEMPLATE.md \
  .github/workflows/codeql.yml \
  .github/workflows/scorecard.yml \
  scripts/capture-release-evidence.sh \
  scripts/promote-release-images.sh \
  scripts/verify-live-release-evidence.sh \
  scripts/verify-release-evidence.py \
  scripts/verify-release-tag.sh; do
  if [[ ! -s "${required}" ]]; then
    echo "✗ 缺少安全基线文件：${required}" >&2
    failed=1
  fi
done
if ! python3 - <<'PY'
from pathlib import Path
import re
import sys

bad: list[str] = []
uses_re = re.compile(r"^\s*(?:-\s*)?uses:\s*([^\s#]+)")
sha_re = re.compile(r"^[^@]+@[0-9a-f]{40}$")
docker_re = re.compile(r"^docker://[^@]+@sha256:[0-9a-f]{64}$")
for workflow in sorted(Path(".github/workflows").glob("*.y*ml")):
    text = workflow.read_text(encoding="utf-8")
    if re.search(r"^\s*pull_request_target\s*:", text, re.MULTILINE):
        bad.append(f"{workflow}: pull_request_target is forbidden")
    if re.search(r"^\s*permissions\s*:\s*write-all\s*$", text, re.MULTILINE):
        bad.append(f"{workflow}: write-all permissions are forbidden")
    for number, line in enumerate(text.splitlines(), 1):
        match = uses_re.match(line)
        if not match:
            continue
        ref = match.group(1)
        if ref.startswith("./") or sha_re.fullmatch(ref) or docker_re.fullmatch(ref):
            continue
        bad.append(f"{workflow}:{number}: action must use a full immutable SHA: {ref}")

if bad:
    print("\n".join(bad), file=sys.stderr)
    raise SystemExit(1)
PY
then
  echo "✗ GitHub Actions 安全基线未通过" >&2
  failed=1
fi

echo "▶ 检查镜像来源与发布 provenance 门禁"
if ! python3 - <<'PY'
from pathlib import Path
import re

errors: list[str] = []
digest_ref = re.compile(r"^[^\s@]+@sha256:[0-9a-f]{64}$")

for dockerfile_name in ("backend/Dockerfile", "nginx/Dockerfile"):
    for number, line in enumerate(
        Path(dockerfile_name).read_text(encoding="utf-8").splitlines(), 1
    ):
        words = line.split()
        if words and words[0].upper() == "FROM":
            image = words[1]
            if image != "scratch" and not digest_ref.fullmatch(image):
                errors.append(f"{dockerfile_name}:{number}: mutable FROM {image}")

compose = Path("docker-compose.app.yml").read_text(encoding="utf-8")
version = Path("VERSION").read_text(encoding="utf-8").strip()
for variable, expected in (
    ("BACKEND_IMAGE", f"apiplatform-backend:{version}"),
    ("NGINX_IMAGE", f"apiplatform-nginx:{version}"),
):
    values = set(re.findall(rf"\$\{{{variable}:-([^}}]+)\}}", compose))
    if values != {expected}:
        errors.append(
            f"docker-compose.app.yml: {variable} default must be versioned as {expected}"
        )
for variable in (
    "POSTGRES_IMAGE",
    "REDIS_IMAGE",
    "PROMETHEUS_IMAGE",
    "GRAFANA_IMAGE",
):
    values = set(re.findall(rf"\$\{{{variable}:-([^}}]+)\}}", compose))
    if len(values) != 1 or not digest_ref.fullmatch(next(iter(values), "")):
        errors.append(
            f"docker-compose.app.yml: {variable} must have one complete RepoDigest default"
        )

release = Path(".github/workflows/release.yml").read_text(encoding="utf-8")
promotion = Path("scripts/promote-release-images.sh").read_text(encoding="utf-8")
capture = Path("scripts/capture-release-evidence.sh").read_text(encoding="utf-8")
live = Path("scripts/verify-live-release-evidence.sh").read_text(encoding="utf-8")
tag_gate = Path("scripts/verify-release-tag.sh").read_text(encoding="utf-8")
attest_action = (
    "actions/attest-build-provenance@"
    "4d101475d8b20a2381f78447822ac1eab6504dd8"
)
if release.count(f"uses: {attest_action}") != 2:
    errors.append("release.yml must provenance-attest exactly two project images")
if release.count("--bundle-from-oci") < 2:
    errors.append("release.yml must verify new and reused provenance from the OCI registry")
if "versions?per_page=100" in release or "grep -Fq '(HTTP 404)'" in release:
    errors.append("release.yml must not infer private/canonical package absence from REST 404")
if "X-GitHub-Api-Version: 2022-11-28" in release or release.count(
    "X-GitHub-Api-Version: 2026-03-10"
) < 5:
    errors.append("release.yml must consistently use the supported 2026-03-10 GitHub REST API version")
for required in (
    "attestations: write",
    "push-to-registry: true",
    "--bundle-from-oci",
    "--signer-workflow",
    "--source-digest",
    "--source-ref",
    "--deny-self-hosted-runners",
    'if [[ "$default_head" != "$GITHUB_SHA" ]]; then',
    "Publish images to unique commit/run/attempt-bound staging tags",
    "Select immutable canonical candidates through the OCI registry",
    "Docker-Content-Digest",
    "Capture exact pre-promotion OCI evidence",
    "Promote or revalidate exact canonical image tags",
    "Re-capture post-promotion OCI evidence",
    "staging-${version}-${GITHUB_SHA}-${GITHUB_RUN_ID}-${GITHUB_RUN_ATTEMPT}",
    "docker push did not report exactly one complete staging digest",
    "Scan selected backend digest for all CRITICAL vulnerabilities",
    "Scan selected web digest for all CRITICAL vulnerabilities",
    "Normalize SBOM metadata to the release commit and digest",
    "attest_exact_sbom_if_missing",
    "release_tag_object_sha: ${{ steps.release_tag.outputs.tag_object_sha }}",
    "EXPECTED_TAG_OBJECT_SHA: ${{ needs.verified-main-ci.outputs.release_tag_object_sha }}",
    "publish-release:",
    "artifact-ids: ${{ needs.signed-images.outputs.artifact_id }}",
    "Install checksum-pinned Cosign without a third-party action",
    "scripts/verify-release-evidence.py",
    "scripts/verify-live-release-evidence.sh",
    "verify_release_tag_identity",
    "verify_canonical_image_tags",
    "verify_live_oci_evidence",
):
    if required not in release:
        errors.append(f"release.yml provenance verification missing: {required}")

offline = Path("build-offline.sh").read_text(encoding="utf-8")
for required in (
    "compose_default_image",
    "require_repo_digest",
    "UNSIGNED_USER_BUILD",
    "rev-parse --verify HEAD^{commit}",
    "BUILD_VARIANT_SHA256",
    "content_tag_for",
    "bind_content_tag",
    "copy_tracked_release_file",
    "git -C \"${ROOT}\" ls-files --error-unmatch",
    "pip download --require-hashes -r /requirements.lock",
):
    if required not in offline:
        errors.append(f"build-offline.sh immutable-source gate missing: {required}")
for forbidden in ('cp -r monitoring', 'cp -r postgres'):
    if forbidden in offline:
        errors.append(f"build-offline.sh must not recursively copy source directories: {forbidden}")
if "grep -Ev '^release/'" in offline:
    errors.append("build-offline.sh must not exempt untracked release/ content from the clean-tree gate")
dockerignore = Path(".dockerignore").read_text(encoding="utf-8").splitlines()
if "/release/" not in dockerignore:
    errors.append(".dockerignore must exclude local release/ artifacts from remote BuildKit contexts")

if release.find("Attest the exact normalized image SBOMs") > release.find(
        "Require anonymous access to linked Community packages"):
    errors.append("release.yml package visibility gate must run after signatures/attestations")
if release.find("Capture exact pre-promotion OCI evidence") > release.find(
        "Promote or revalidate exact canonical image tags"):
    errors.append("release.yml must capture verified OCI evidence before promotion")
if release.find("Re-capture post-promotion OCI evidence") > release.find(
        "Require anonymous access to linked Community packages"):
    errors.append("release.yml must promote and re-resolve exact digests before visibility/release")
if 'docker push "$BACKEND_IMAGE"' in release or 'docker push "$WEB_IMAGE"' in release:
    errors.append("release.yml must not unconditionally overwrite immutable version tags")
if promotion.count('bash "${ROOT}/scripts/verify-release-tag.sh"') != 2:
    errors.append("promotion must recheck the release tag/default HEAD before and after")
if "--prefer-index=false" not in promotion or "Docker-Content-Digest" not in promotion:
    errors.append("promotion must copy and re-resolve one exact OCI manifest digest")
if "versions?per_page=100" in promotion or "(HTTP 404)" in promotion:
    errors.append("promotion must resolve canonical state through authenticated OCI operations")
for text_name, text in (("capture", capture), ("live", live)):
    for required in (
        '--signer-digest "${GITHUB_SHA}"',
        '--source-digest "${GITHUB_SHA}"',
        '--source-ref "${GITHUB_REF}"',
        "--deny-self-hosted-runners",
    ):
        if required not in text:
            errors.append(f"{text_name} evidence gate missing: {required}")
if "require_snapshot_subset()" not in live or ".predicate == $sbom[0]" not in live:
    errors.append("live OCI verifier must bind immutable referrer snapshots and exact SBOM")
if ".default_branch" not in tag_gate or ".object.sha == $expected_commit" not in tag_gate:
    errors.append("release tag gate must keep the commit at exact default-branch HEAD")

if errors:
    raise SystemExit("\n".join(errors))
PY
then
  echo "✗ 镜像来源或 provenance 门禁未通过" >&2
  failed=1
fi
if ! bash scripts/test-offline-package-verify.sh; then
  echo "✗ 离线包 fail-closed 回归测试未通过" >&2
  failed=1
fi
if ! python3 scripts/test-release-supply-chain.py; then
  echo "✗ release staging/promotion 回归测试未通过" >&2
  failed=1
fi
if ! bash -n \
  scripts/capture-release-evidence.sh \
  scripts/promote-release-images.sh \
  scripts/verify-live-release-evidence.sh \
  scripts/verify-release-tag.sh; then
  echo "✗ release supply-chain shell syntax check failed" >&2
  failed=1
fi

echo "▶ 检查生产依赖顶层 pin 与哈希锁文件"
if ! python3 scripts/check-requirements-lock.py || \
   ! python3 scripts/test-requirements-lock-sync.py; then
  echo "✗ backend/requirements.txt 与 requirements.lock 未同步" >&2
  failed=1
fi

echo "▶ 检查开源/商业版文件边界"
if [[ ! -f EDITION.json ]] || ! python3 - <<'PY'
import json
from pathlib import Path

edition = json.loads(Path("EDITION.json").read_text(encoding="utf-8"))
assert edition.get("edition") == "community"
assert edition.get("repositoryVisibility") == "public"
assert edition.get("license") == "Apache-2.0"
assert edition.get("commercialSourceIncluded") is False
assert str(edition.get("extensionApi", "")) == "1"
PY
then
  echo "✗ EDITION.json 未明确声明公开 Apache-2.0 社区版边界" >&2
  failed=1
fi
if git ls-files 'enterprise/**' 'commercial/**' 'proprietary/**' | grep -q .; then
  echo "✗ 公开仓库中出现企业版源码目录；商业实现必须留在私有仓库" >&2
  git ls-files 'enterprise/**' 'commercial/**' 'proprietary/**' >&2
  failed=1
fi

echo "▶ 检查私钥标记"
if rg -n --with-filename --hidden -S \
  -e '-----BEGIN [A-Z ]*PRIVATE KEY-----' \
  --glob '!.git/**' \
  --glob '!**/node_modules/**' \
  --glob '!**/.venv/**' \
  --glob '!frontend/dist/**' \
  --glob '!offline-images/**' \
  --glob '!scripts/check-public-release.sh' \
  .; then
  echo "✗ 发现私钥标记；上述文件不得进入公开发行包" >&2
  failed=1
fi

echo "▶ 检查常见明文令牌与原组织标识"
if rg -n --with-filename --hidden -S \
  -e 'AKIA[0-9A-Z]{16}' \
  -e 'gh[pousr]_[A-Za-z0-9]{30,}' \
  -e 'sk-[A-Za-z0-9_-]{24,}' \
  -e 'BRDC\.ai|大数据应用部|\bdpmp\b' \
  --glob '!.git/**' \
  --glob '!**/node_modules/**' \
  --glob '!**/.venv/**' \
  --glob '!frontend/dist/**' \
  --glob '!scripts/check-public-release.sh' \
  .; then
  echo "✗ 发现疑似令牌或原组织标识；请逐项确认并清理" >&2
  failed=1
fi

echo "▶ 检查数据库导出与本地密钥文件"
while IFS= read -r path; do
  echo "✗ 不得发布：${path}" >&2
  failed=1
done < <(
  find . -type f \
    \( -iname '*.dump' -o -iname '*.backup' -o -iname '*.sql' -o -name '.env' \
       -o -iname '*.pem' -o -iname '*.key' -o -iname '*.p12' -o -iname '*.pfx' \) \
    -not -path './.git/*' \
    -not -path '*/node_modules/*' \
    -not -path '*/.venv/*' \
    -not -path './offline-images/*' \
    -print
)

echo "▶ 检查本地构建缓存"
while IFS= read -r path; do
  echo "✗ 发布前应移除本地缓存：${path}" >&2
  failed=1
done < <(
  find . \
    \( -path './.git' -o -path '*/node_modules' -o -path '*/.venv' \) -prune -o \
    -type f \( -name '*.pyc' -o -name '*.pyo' -o -name '.DS_Store' \) -print
)

if git ls-files '*.dump' '*.backup' '*.sql' | grep -q .; then
  echo "✗ Git 索引中存在数据库导出文件" >&2
  git ls-files '*.dump' '*.backup' '*.sql' >&2
  failed=1
fi

echo "▶ 检查 Git 历史对象路径"
history_paths="$({ git rev-list --objects --all || true; } | awk '{$1=""; sub(/^ /, ""); print}')"
if printf '%s\n' "${history_paths}" | rg -n -i \
  '(^|/)(\.env|bak)(/|$)|\.(dump|backup|sql|pem|p12|pfx)$|brdc|dpmp'; then
  echo "✗ Git 历史仍包含敏感/内部资产路径；请从干净仓库发布或验证历史重写" >&2
  failed=1
fi

git diff --check

if (( failed )); then
  exit 1
fi
echo "✔ 当前源码快照通过开源发布检查"
